version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  elasticsearch:
    image: elasticsearch
    ports:
     - 9200:9200
     - 9300:9300
    environment:
      discovery.type: single-node